### ISSUE TITLE
BUG: some searchable articles cannot be opened

### ISSUE THREAD

**Issue by soshial** [itkach/aard2-web#15] opened 2023-06-06 07:18 UTC
Search `curl "http://127.0.0.1:8013/find/?key=min"` -> "minaret" and "mind" are found.

```json
[ {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "min",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/min?blob=218-83#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "min min",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/min%20min?blob=218-230#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "min.",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/min.?blob=218-84#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minable",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minable?blob=218-125#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minacious",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minacious?blob=218-85#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minamata disease",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minamata%20disease?blob=218-86#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minangkabau",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minangkabau?blob=218-87#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minaret",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minaret?blob=218-88#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minas gerais",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minas%20gerais?blob=218-89#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minatory",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minatory?blob=218-90#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minaudiere",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minaudiere?blob=218-91#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minbar",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minbar?blob=218-92#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mince",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mince?blob=218-93#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mince pie",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mince%20pie?blob=218-96#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minced",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minced?blob=218-94#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mincemeat",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mincemeat?blob=218-95#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minch",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minch?blob=218-97#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mincing",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mincing?blob=218-98#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind?blob=218-99#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind altering",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20altering?blob=218-100#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind bender",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20bender?blob=218-102#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind blowing",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20blowing?blob=218-103#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind boggling",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20boggling?blob=218-104#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind expanding",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20expanding?blob=218-109#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind fuck",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20fuck?blob=218-110#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind game",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20game?blob=218-113#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind map",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20map?blob=218-117#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind numbing",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20numbing?blob=218-118#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind one's own business",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20one's%20own%20business?blob=48-160#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind read",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20read?blob=218-120#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind set",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20set?blob=218-121#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind share",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20share?blob=218-122#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mind your own business",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mind%20your%20own%20business?blob=218-123#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindanao",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindanao?blob=218-101#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minded",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minded?blob=218-105#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindedness",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindedness?blob=218-106#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindel",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindel?blob=218-107#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minder",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minder?blob=218-108#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindful",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindful?blob=218-111#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindfulness",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindfulness?blob=218-112#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindi",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindi?blob=218-114#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindless",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindless?blob=218-115#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindlessly",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindlessly?blob=218-116#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mindoro",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mindoro?blob=218-119#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine?blob=218-124#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine detector",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20detector?blob=218-126#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine dump",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20dump?blob=218-127#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine field",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20field?blob=218-128#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine host",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20host?blob=165-200#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine hunter",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20hunter?blob=218-129#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine layer",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20layer?blob=218-130#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine proof",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20proof?blob=218-131#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine shaft",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20shaft?blob=218-147#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine sweeper",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20sweeper?blob=218-149#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine worker",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20worker?blob=218-150#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mine working",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mine%20working?blob=218-151#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "miner",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/miner?blob=218-132#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "miner",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/miner?blob=218-133#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "miner's right",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/miner's%20right?blob=218-144#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineral",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineral?blob=218-134#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineral oil",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineral%20oil?blob=218-138#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineral rights",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineral%20rights?blob=218-139#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineral spirits",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineral%20spirits?blob=218-140#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineral spring",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineral%20spring?blob=218-141#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineral water",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineral%20water?blob=218-142#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineral wool",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineral%20wool?blob=218-143#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineralisation",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineralisation?blob=218-135#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineralocorticoid",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineralocorticoid?blob=218-136#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mineralogical",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mineralogical?blob=218-137#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minerva",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minerva?blob=218-145#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minervois",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minervois?blob=218-146#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minestrone",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minestrone?blob=218-148#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "ming",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/ming?blob=218-152#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minge",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minge?blob=218-153#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minger",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minger?blob=218-154#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mingier",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mingier?blob=218-159#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minging",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minging?blob=218-155#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mingle",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mingle?blob=218-156#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mingler",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mingler?blob=218-157#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mingus",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mingus?blob=218-158#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minhag",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minhag?blob=218-160#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "minho",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/minho?blob=218-161#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini?blob=218-162#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini?blob=218-163#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini bar",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20bar?blob=218-169#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini beast",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20beast?blob=218-170#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini break",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20break?blob=218-171#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini bus",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20bus?blob=218-172#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini cab",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20cab?blob=218-173#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini cam",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20cam?blob=218-174#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini camp",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20camp?blob=218-175#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini computer",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20computer?blob=218-177#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini disc",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20disc?blob=218-179#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini dress",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20dress?blob=218-180#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini golf",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20golf?blob=218-182#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini mall",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20mall?blob=218-189#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini market",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20market?blob=218-191#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini mart",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20mart?blob=218-192#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini me",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20me?blob=218-194#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini moon",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20moon?blob=218-197#"
}, {
  "dictLabel" : "Oxford Dictionary of English",
  "label" : "mini pill",
  "url" : "/slob/c5350107-4853-4dad-a113-11e71f05fb9d/mini%20pill?blob=218-208#"
} ]
```

Search by "mina" and "mind" -> these articles are not found.
curl "http://127.0.0.1:8013/find/?key=mina"
[ ]
curl "http://127.0.0.1:8013/find/?key=mind"
[ ]

**Comment by itkach** [comment] 2023-06-06 14:26
I am unable to reproduce this with aard2-web-0.9. I assume you compiled [this xdxf dictionary](https://sourceforge.net/projects/xdxf/files/dicts-XDXF/dsl03/comn_dls03_mwc.tar.bz2/download) with [xdxf2slob](https://github.com/itkach/xdxf2slob/). I did the same and finding results for "mina" and "mind". 

I wonder which version of ICU and PyICU was used for your dictionary? Check `version.icu` and `version.pyicu` dictionary tags. Mine is 

```
version.icu   72.1
version.pyicu 2.11
```

I also have an old copy of the same dictionary with 

```
version.icu   52.1
version.pyicu 1.8
```

which also work as expected.

**Comment by soshial** [comment] 2023-06-06 17:36
Nope, I actually installed [pyglossary](https://github.com/ilius/pyglossary) and converted AppleDict binary dictionary into Aard2Slob. Here's the source file (copied from macOS) and the output slob: [HERE](https://mega.nz/folder/j0p2iTzb#0wY4UY6KuYNCpNmDVGb62g).

```
./venv/bin/python3.11 -m pip list
Package        Version
-------------- -------
biplist        1.0.3
lxml           4.9.2
pip            23.1.2
prompt-toolkit 3.0.38
PyICU          2.11
setuptools     65.5.1
wcwidth        0.2.6
wheel          0.38.4
```

slob info:
```
/Users/soshial/Desktop/Oxford_Dictionary_of_English.slob
--------------------------------------------------------
         id: 1338fc57bfa54006b354c56ea3b75825
   encoding: utf-8
compression: zlib
 blob count: 114149
  ref count: 321709


CONTENT TYPES
-------------
text/css
application/pdf
text/html; charset=utf-8


TAGS
----
    created.at: 2023-06-06T10:29:45.282829+00:00
version.python: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
 version.pyicu: 2.11
   version.icu: 72.1
         label: Oxford Dictionary of English
```

**Comment by itkach** [comment] 2023-06-06 20:06
I see. That dictionary appears to be very broken, not just in aard2-web but also [with the reference implementation]( https://github.com/itkach/slob). I am not sure why is that - pyglossary is using [slob](https://github.com/itkach/slob) for writing, seemingly in a straightforward way, and [slob](https://github.com/itkach/slob) is not known to produce broken dictionaries like that. In fact re-creating the dictionary with  [slob](https://github.com/itkach/slob) fixes it:

```
slob convert -b 512 Oxford_Dictionary_of_English.slob -c lzma2 Oxford_Dictionary_of_English_2.slob
```

**Comment by soshial** [comment] 2023-06-07 08:19
Thank you so much for looking into the corrupted Slob file! Looks like the problem was because [we refactored ](https://github.com/ilius/pyglossary/commit/ce027ecb87696b049151d52d2f88cedf801c1262) the `slob.py` incorporated into pyglossary codebase.

Is it possible to have [slob](https://github.com/itkach/slob) as a Python library installed via `pip` directly from catalog like pypi?

**Comment by itkach** [comment] 2023-06-09 00:39
> Is it possible to have [slob](https://github.com/itkach/slob) as a Python library installed via `pip` directly from catalog like pypi?

Yes, it is possible to include it as a dependency [by pointing directly to Github repo](https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repository-as-a-dependency/54701434#54701434).

**Comment by itkach** [comment] 2023-06-09 14:25
resolved in https://github.com/ilius/pyglossary/issues/458

**Closed as completed by itkach** 2023-06-09 14:25 UTC
